GET http://localhost:8000/api/authors HTTP/1.1

###
POST http://localhost:8000/api/authors HTTP/1.1
Content-Type: application/json

{
    "name":"Bill Bryson"
}

###
GET http://localhost:8000/api/authors/605fa9adc313bceaa3a4263c HTTP/1.1

###
PUT http://localhost:8000/api/authors/605fa9adc313bceaa3a4263c HTTP/1.1
Content-Type: application/json

{
    "name":"Bill Bryson"
}

###
DELETE http://localhost:8000/api/authors/605fa9adc313bceaa3a4263c HTTP/1.1